Fixes to get the CD working again
cellml/libcellml pull request #1008
Opened 2022-07-18 08:26 UTC by hsorby

2022-07-19 01:05 UTC, agarny reviewed
This seems fine. Just a few minor comments.

Otherwise, regarding the generation of wheels, why not use `cibuildwheel`?

2022-07-19 01:05 UTC, agarny commented on README.rst
> +  :target: https://github.com/hsorby/l1bcellml/actions/workflows/deploy-on-release.yml
`cellml` rather than `hsorby`?

2022-07-19 01:05 UTC, agarny commented on .github/workflows/deploy-on-release.yml
> +            name: "macOS 12.4 Clang Py38", deploy_libs: false, deploy_python: true,
Replace `12.4` with `12` or `12.x` (same at line 188) in case there is a newer 12.x version?

2022-07-19 01:05 UTC, agarny commented on .github/workflows/deploy-on-release.yml
> +            zlib_dir: '-D "ZLIB_DIR=../usr/local/ZLIB-1.2.3/CMake/"',
Replace `..` with `$GITHUB_WORKSPACE` (same at lines 172-173) to be consistent (and bullet-proof) with what has been done at line 526 for instance?

2022-07-27 03:27 UTC, hsorby commented on .github/workflows/deploy-on-release.yml
> +            name: "macOS 12.4 Clang Py38", deploy_libs: false, deploy_python: true,
I use 12.4 here because it is the version of the virtual machine from GitHub actions.

2022-07-27 03:32 UTC, hsorby commented on .github/workflows/deploy-on-release.yml
> +            zlib_dir: '-D "ZLIB_DIR=../usr/local/ZLIB-1.2.3/CMake/"',
I can't use environment variables here for the matrix strategy we are stuck with this, unless we want to get super fancy and create a dynamic matrix.

2022-08-04 04:24 UTC, agarny commented on README.rst
> +  :target: https://github.com/hsorby/l1bcellml/actions/workflows/deploy-on-release.yml
I understand that this will eventually get changed, so resolving.

2022-08-04 04:37 UTC, hsorby commented on README.rst
> +  :target: https://github.com/hsorby/l1bcellml/actions/workflows/deploy-on-release.yml
When I look at the changes it shows the correct GitHub project location.

2022-08-04 06:23 UTC, agarny commented on README.rst
> +  :target: https://github.com/hsorby/l1bcellml/actions/workflows/deploy-on-release.yml
Oops, I hadn't bothered looking thinking it was one of those that might need to be done after merging in or something. Anyway, I can now see that it's ok. :)

2022-08-04 06:29 UTC, agarny requested changes
Looks ok, just some minor suggestions.

2022-08-04 06:29 UTC, agarny commented on cmake/environmentchecks.cmake
> +endif()
Woudl rework this to have only one conditional statement..

2022-08-04 06:29 UTC, agarny commented on src/bindings/python/setup.py
> +    #package_data={'libcellml': ['libcellml.0.2.0-dev.24.dylib', '_analyser.so', '_analyserequation.so', '_analyserequationast.so', '_analyserexternalvariable.so', '_analysermodel.so', '_analyservari
Remove?

2022-08-04 06:29 UTC, agarny commented on src/bindings/python/setup.py
> +    #cmake_install_dir="libcellmlXXXXXX",
Remove?

2022-08-04 09:24 UTC, agarny submitted a review, later dismissed

2022-08-08 12:02 UTC, nickerso approved these changes
Seem to be a few random whitespace changes in the tests and a new test added for coverage purposes that are likely nothing to do with getting the CD working, but not worth pulling them into a separate PR at this point.

2022-08-08 21:31 UTC, agarny approved these changes
Just one comment that is not directly linked to this PR and which doesn't affect this PR, so approving as-is. (Might still want to address the comment at some point though.)

2022-08-08 21:31 UTC, agarny commented on tests/model/model.cpp
> +    // Testing copy constructor
I guess it's not critical for our tests, but in our codebase we would have a full stop at the end of a comment.

2022-08-08 21:31 UTC, merged