Debug utilities library installation
cellml/libcellml pull request #1058
Opened 2022-11-28 08:17 UTC by hsorby

Fixes #980.

I have also added a test to try and detect if the debug utilities is being used by the libCellML library. It of course shouldn't be, it is only to be used for debugging.

2022-11-29 10:40 UTC, agarny requested changes
Just a minor change otherwise all good.

2022-11-29 10:40 UTC, agarny commented on tests/CMakeLists.txt
> +add_test(NAME are_debug_utilities_not_being_used COMMAND ${CMAKE_COMMAND} -P ${CMAKE_SOURCE_DIR}/cmake/checkfordebugheaderusage.cmake ${ALL_LIBRARY_SOURCE_FILES})
Might just want to rename that test to `are_debug_utilities_used`. It's not like that we are testing the return value of something.

2022-11-29 21:24 UTC, agarny approved these changes

2022-11-30 08:30 UTC, nickerso approved these changes

2022-11-30 17:23 UTC, merged