Analyser: don't optimise the order of variables and equations
cellml/libcellml pull request #1090
Opened 2023-01-27 03:07 UTC by agarny

Fixes #1089.

2023-01-29 09:46 UTC, hsorby commented
Was this [commit](https://github.com/cellml/libcellml/pull/1090/commits/ed7cbda364a60218d3f82c469b3ef9333ac377c9) added to the correct PR?

2023-01-29 19:25 UTC, agarny commented
> Was this [commit](https://github.com/cellml/libcellml/pull/1090/commits/ed7cbda364a60218d3f82c469b3ef9333ac377c9) added to the correct PR?

Oops, you are completely right! Have just cherry picked it for PR #1080 (see commit 356e1707).

2023-04-26 05:24 UTC, hsorby requested changes

2023-04-26 05:24 UTC, hsorby commented on tests/coverage/coverage.cpp
> +                  analyserModel->variable(i)->initialisingVariable() != nullptr);
Weird testing condition, I would prefer:
```
if ((i == 1) || (i == 2) || (i == 6) || (i == 18) || (i == 177) || (i == 178) || (i == 180)) {
    EXPECT_TRUE(analyserModel->variable(i)->initialisingVariable() != nullptr);
}
```

2023-04-26 05:24 UTC, hsorby commented on tests/resources/coverage/generator/model.implementation.out
I don't understand why this file has the suffix `.out`.

2023-04-26 05:24 UTC, hsorby commented on tests/resources/coverage/generator/model.out
I don't understand why this file has the suffix `.out`.

2023-04-26 05:53 UTC, agarny commented on tests/resources/coverage/generator/model.implementation.out
Just an `out`put file.

2023-04-26 05:53 UTC, agarny commented on tests/resources/coverage/generator/model.out
Just an `out`put file.

2023-04-26 05:59 UTC, agarny commented on tests/coverage/coverage.cpp
> +                  analyserModel->variable(i)->initialisingVariable() != nullptr);
ce85080f

2023-04-26 06:14 UTC, nickerso approved these changes, later dismissed

2023-04-26 06:38 UTC, nickerso approved these changes

2023-04-26 06:51 UTC, hsorby approved these changes

2023-04-26 07:03 UTC, merged