Fix segfault with imports across multiple directories
cellml/libcellml pull request #1304
Opened 2024-11-20 22:08 UTC by hsorby

It appears the importer is not matching units correctly when importing units across multiple directories.

Fixes #1302.

2024-11-21 21:22 UTC, agarny requested changes
Looks fine pending one minor change.

2024-11-21 21:22 UTC, agarny commented on tests/test_utils.cpp
> +    if (c == size_t(-1)) {
I would replace `size_t(-1)` with `std::numeric_limits<size_t>::max()` or maybe even `SIZE_MAX` if we are ok using a `#define`.

2024-11-21 21:56 UTC, hsorby commented on tests/test_utils.cpp
> +    if (c == size_t(-1)) {
[bd0b2e9](https://github.com/cellml/libcellml/pull/1304/commits/bd0b2e98adea5483741a0bad26cf7ece07c685cd)

2024-11-21 22:03 UTC, agarny approved these changes

2024-11-24 19:57 UTC, nickerso approved these changes

2024-11-24 20:48 UTC, merged