Use `create` method for object construction only
cellml/libcellml pull request #460
Opened 2019-11-16 01:14 UTC by hsorby

This work forces the use of the `create` method for constructing new objects for all classes in the library.

Addresses #458.

2019-11-19 08:26 UTC, hsorby commented
Ready for review.

2019-11-19 19:45 UTC, agarny commented on src/api/libcellml/component.h
> +     *   ComponentPtr component = libcellml::Component::create(std::string("Component"));
Might want to simplify this a bit:

```
ComponentPtr component = libcellml::Component::create("Component");
```

2019-11-19 19:50 UTC, agarny commented on src/api/libcellml/model.h
> +     *   ModelPtr model = libcellml::Model::create(std::string("Model"));
Simplify with:

```
ModelPtr model = libcellml::Model::create("Model");
```

2019-11-19 19:51 UTC, agarny commented on src/api/libcellml/reset.h
> +     * or an ordered reset with order "10" with::
Drop the double quotes, it's not a string.

2019-11-19 20:03 UTC, agarny requested changes
Looks good, pending some (very) minor issues.

2019-11-19 20:03 UTC, agarny commented on src/api/libcellml/variable.h
> +     *   VariablePtr variable = libcellml::Variable::create("Variable");
Simplify with:

```
VariablePtr variable = libcellml::Variable::create("Variable");
```

2019-11-19 21:41 UTC, agarny approved these changes

2019-11-20 01:19 UTC, nickerso commented
Its not clear to me why different objects have different `create` methods. It maybe makes sense that classes derived from `NamedEntity` have a create method with a `name` argument, but why a `Reset` create with an `order` attribute? Or perhaps why no `Variable` create method with name and units? (or did I miss it?)

2019-11-20 01:37 UTC, hsorby commented
> Its not clear to me why different objects have different `create` methods. It maybe makes sense that classes derived from `NamedEntity` have a create method with a `name` argument, but why a `Reset` create with an `order` attribute? Or perhaps why no `Variable` create method with name and units? (or did I miss it?)

I have added some convenience methods to see how they would work.  A `Reset` must have an order set so it seemed useful to have a method that allowed the creation of a `Reset` with an order.

I haven't done all possible convenience methods just the ones that I thought about as I modified the `create` method.  'Missing' convenience methods can be added at any time for those that have been missed.

2019-11-20 01:45 UTC, nickerso approved these changes

2019-11-20 01:47 UTC, merged

2019-11-20 08:17 UTC, kerimoyle commented
I'd have thought that having a reset with the test_variable and the reset_variable made more sense as a constructor than the order alone ... but as you say, there are a whole load of combinations ...

2019-11-20 21:14 UTC, hsorby commented
These are all good ideas we should probably put them into an issue on convenience constructors :)