Dealing with standard units.
cellml/libcellml pull request #547
Opened 2020-02-19 08:16 UTC by hsorby

This PR looks at defining the way units are handled that are standard units.  The two tests show the new behaviour.

Addresses issue #545.

2020-02-19 08:38 UTC, kerimoyle commented
See also #525 and pr #526?

On Wednesday, 19 February 2020, Hugh Sorby <notifications@github.com> wrote:

> This PR looks at defining the way units are handled that are standard
> units. The two tests show the new behaviour.
>
> Addresses issue #545 <https://github.com/cellml/libcellml/issues/545>.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cellml/libcellml/pull/547
> Commit Summary
>
>    - Add test for finding scaling factors where one of the units is a
>    standard unit.
>    - Determine scaling factor when one of the units is a standard units.
>    - Reformat code according to clang format.
>    - Add test to show what happens when a 'standard' unit is added to a
>    model.
>    - Add isStandardUnits() function.
>    - Make use of isStandardUnit function. Don't print out standard units
>    in a model.
>
> File Changes
>
>    - *M* src/model.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-0> (4)
>    - *M* src/printer.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-1> (2)
>    - *M* src/units.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-2> (2)
>    - *M* src/utilities.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-3> (10)
>    - *M* src/utilities.h
>    <https://github.com/cellml/libcellml/pull/547/files#diff-4> (2)
>    - *M* tests/parser/parser.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-5> (18)
>    - *M* tests/printer/printer.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-6> (17)
>    - *M* tests/units/units.cpp
>    <https://github.com/cellml/libcellml/pull/547/files#diff-7> (10)
>
> Patch Links:
>
>    - https://github.com/cellml/libcellml/pull/547.patch
>    - https://github.com/cellml/libcellml/pull/547.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cellml/libcellml/pull/547?email_source=notifications&email_token=ALFXCNH3JF4LLMKT2LVIL3LRDTTEJA5CNFSM4KXUEOGKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IORWXSA>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALFXCNBPX4AQ6NPVFUZQKV3RDTTEJANCNFSM4KXUEOGA>
> .
>

2020-02-19 20:54 UTC, agarny commented on src/printer.cpp
> +        // Do nothing
Missing full stop at the end of the comment.

2020-02-19 20:54 UTC, agarny commented on src/utilities.cpp
> +    return is; //standardUnitsList.count(name) != 0;
Why that comment? I would delete it.

Having said that, I would rewrite the whole method to simply read:

```
bool isStandardUnit(const UnitsPtr &units)
{
    if ((units != nullptr) && units->isBaseUnit() && isStandardUnitName(units->name())) {
        return true;
    }

    return false;
}
```

2020-02-19 20:54 UTC, agarny commented on src/utilities.h
> +bool isStandardUnit(const UnitsPtr &units);
Need some documentation for this new method.

2020-02-19 20:54 UTC, agarny commented on tests/printer/printer.cpp
> +    libcellml::ModelPtr model = libcellml::Model::create("my_model");
Minor: might want to swap those two lines? (Just feels "weird" to create a units before a model.)

2020-02-19 20:55 UTC, agarny requested changes
Looks fine to me pensing some minor issues.

2020-02-20 00:39 UTC, agarny approved these changes

2020-02-21 03:16 UTC, nickerso approved these changes

2020-02-21 03:16 UTC, merged