i594 Validator should not check dummy variables in imported components
cellml/libcellml pull request #605
Opened 2020-05-27 02:04 UTC by kerimoyle

Addresses #594 

When you create a connection to a dummy variable prior to flattening a model with imports, the dummy variables are being checked for interface types and units.  They should be skipped ...

- [ ] Test to show behaviour
- [ ] Fix it all :)

2020-05-27 04:01 UTC, kerimoyle commented
Ready for review please.  @agarny @hsorby @nickerso .  Should be pretty quick and easy ... :)

2020-06-10 20:53 UTC, kerimoyle commented
Updated and ready for review please @agarny @nickerso @hsorby

2020-06-10 21:24 UTC, agarny commented on src/validator.cpp
> +        // If the parent component of the variable is imported, don't check it.
Replace with (or something similar):
```
// If the equivalent variable doesn't have a parent component or its parent component is imported then don't check it.
```

2020-06-10 21:24 UTC, agarny commented on src/validator.cpp
> +        auto equivalentComponent = std::dynamic_pointer_cast<Component>(equivalentVariable->parent());
Nice candidate for our forthcoming `owningComponent()`. :) (Same below.)

2020-06-10 21:24 UTC, agarny commented on src/validator.cpp
> +        }
I would replace this with:
```
if ((equivalentComponent == nullptr) || equivalentComponent->isImport()) {
    continue;
}
```

2020-06-10 21:28 UTC, agarny commented on tests/validator/validator.cpp
> +    // checks the dummyVariable and fails the model.
I must be missing something: how is that failing the model? `dummyVariable` is imported so it won't be checked during validation, right? And, indeed, the validator doesn't have any issues. So, is the comment wrong here?

2020-06-10 21:29 UTC, agarny requested changes
Looks good.

2020-06-10 21:45 UTC, kerimoyle commented on tests/validator/validator.cpp
> +    // checks the dummyVariable and fails the model.
Leftover ... this is the behaviour that was fixed. 43c9e0a3

2020-06-10 21:45 UTC, kerimoyle commented on src/validator.cpp
> +        }
43c9e0a3

2020-06-10 21:45 UTC, kerimoyle commented on src/validator.cpp
> +        // If the parent component of the variable is imported, don't check it.
43c9e0a3

2020-06-10 21:51 UTC, agarny commented on tests/validator/validator.cpp
> +    libcellml::Variable::addEquivalence(variable, dummyVariable);
Might want to add a quick comment that although we add an equivalence, the equivalent variable still doesn't get checked because it's imported.

Otherwise, it might be good to add `dummyVariable` to `dummyComponent` after the call to `addEquivalence()`, so that we also test the case when the equivalent variable doesn't have a component parent?

2020-06-10 22:31 UTC, kerimoyle commented on tests/validator/validator.cpp
> +    libcellml::Variable::addEquivalence(variable, dummyVariable);
> Might want to add a quick comment that although we add an equivalence, the equivalent variable still doesn't get checked because it's imported.

It's in the comment a few lines higher?

> Otherwise, it might be good to add dummyVariable to dummyComponent after the call to addEquivalence(), so that we also test the case when the equivalent variable doesn't have a component parent?

That's a little out of scope for this PR?  It's nothing to do with importing ... and we already have `Validator, validateInvalidConnectionsVariableWithoutParentComponent` and `Connection, componentlessVariableInvalidConnection` for that purpose.

2020-06-10 22:54 UTC, agarny commented on src/validator.cpp
> +                ComponentPtr parentComponent = std::dynamic_pointer_cast<Component>(variable->parent());
Should now use `owningComponent()` (same elsewhere).

2020-06-10 23:23 UTC, kerimoyle commented on src/validator.cpp
> +                ComponentPtr parentComponent = std::dynamic_pointer_cast<Component>(variable->parent());
This will be true all over the place ... so should be checked as a separate issue.

2020-06-10 23:28 UTC, agarny commented
For some reasons, GitHub doesn't allow me to reply to https://github.com/cellml/libcellml/pull/605#discussion_r438460031, so I am doing it here:

This is the reason I have created issue #623. However, this doesn't undermine the fact that this PR should use `owningComponent()` since it's now part of the `develop` branch.

2020-06-10 23:31 UTC, kerimoyle commented
PRs should be specific, otherwise we're never going to get anywhere! (also the reason that you haven't updated all the error messages in the earlier PR? ;) )

2020-06-10 23:34 UTC, agarny commented
This PR adds new code. I would therefore expect that new code to use whatever is available in the `develop` branch. Simple as that. Anyway, will leave it to @nickerso and @hsorby to accept this PR, no problems.

2020-06-10 23:48 UTC, kerimoyle commented
@agarny That's fair enough - I've changed the new code now.  I don't think this PR should have to change all of them though (if anything, that should have been in the earlier one which created the function), and the others will be addressed in your #623

2020-06-10 23:55 UTC, agarny commented
> @agarny That's fair enough - I've changed the new code now. I don't think this PR should have to change all of them though (if anything, that should have been in the earlier one which created the function), and the others will be addressed in your #623

Agreed, only the new code of this PR should use the `owningComponent()` method. The rest of the code will be updated as part of issue #623. (Agreed too that I could have made the forthcoming changes for issue #623 when I introduced `owningComponent()`.)

2020-06-10 23:57 UTC, agarny commented on src/validator.cpp
> +        auto parentComponent = std::dynamic_pointer_cast<Component>(variable->parent());
`owningComponent()` should be used here too.

2020-06-11 00:01 UTC, agarny approved these changes

2020-06-14 20:05 UTC, kerimoyle commented
Ping @hsorby @nickerso

2020-06-30 21:17 UTC, hsorby approved these changes

2020-06-30 21:20 UTC, merged