I770 Update ImportSource when removing/replacing/taking imported items
cellml/libcellml pull request #774
Opened 2020-11-05 03:13 UTC by kerimoyle

Addresses #770 

Depends upon #773

2020-11-05 03:15 UTC, kerimoyle commented
There's a bug in the `Parser` (see #771 ) which is highlighted only when the other bugs around the `ImportSource` are fixed.  That one will probably have to be done as part of this PR too, since it's only manifest when these other things are resolved.

2020-11-09 00:41 UTC, kerimoyle commented
Ready for review please @agarny @hsorby @nickerso (build on MacOS only failing because of waiting for #760 to be merged).

2020-12-07 23:07 UTC, hsorby requested changes, later dismissed
All tests that go `replaceImportedComponentByNameIndexOrReference` should be separate tests `replaceImportedComponentByName`; `replaceImportedComponentByIndex`; `replaceImportedComponentByReference`.

2020-12-07 23:07 UTC, hsorby commented on src/api/libcellml/model.h
> +     * if the optional @p merge parameter is true, the contents of the given @p importSrc
If

2020-12-07 23:07 UTC, hsorby commented on src/componententity.cpp
> +        mPimpl->mComponents.insert(mPimpl->mComponents.begin() + int64_t(index), newComponent);
Should this `int64_t` be `uintptr_t`?

2020-12-09 00:42 UTC, kerimoyle commented on src/componententity.cpp
> +        mPimpl->mComponents.insert(mPimpl->mComponents.begin() + int64_t(index), newComponent);
Perhaps, but if so should be a separate PR as it's everywhere ... and not really related to this PR.  I just changed the name of the component handle so it was easier to understand. 
![image](https://user-images.githubusercontent.com/46887220/101558642-3ce7f400-3a24-11eb-8588-9e3cbd1c9654.png)

2020-12-09 00:43 UTC, kerimoyle commented on src/api/libcellml/model.h
> +     * if the optional @p merge parameter is true, the contents of the given @p importSrc
b82e97c1

2020-12-09 00:44 UTC, kerimoyle commented
Review comments all addressed in b82e97c1.  Ready for review please @hsorby @agarny @nickerso.

2021-01-24 07:07 UTC, hsorby commented
During my review of this PR I thought that we should reimagine how ImportSources are considered.  I have started a [mini-project](https://github.com/cellml/libcellml/projects/5) to capture this possible transition.

2021-03-24 22:17 UTC, merged