Add test where units are expected to be linked after parsing a model
cellml/libcellml pull request #888
Opened 2021-06-30 09:51 UTC by hsorby

Closes #887.

2021-06-30 23:45 UTC, agarny requested changes

2021-06-30 23:45 UTC, agarny commented on tests/parser/file_parser.cpp
> +    printModel(model, false);
Debug code, so remove it.

2021-07-01 00:24 UTC, hsorby commented on tests/parser/file_parser.cpp
> +    printModel(model, false);
8e16b79

2021-07-01 00:26 UTC, agarny approved these changes

2021-07-02 00:33 UTC, nickerso approved these changes

2021-07-02 00:45 UTC, nickerso commented
@hsorby - the error in the coverage looks like the buildbot might have run out of space?

2021-07-02 01:35 UTC, hsorby commented
I don't think so, I think that is a disk failed error.  I think this is due to an error with the virtual disk more than anything.  I'll try a rebuild.

2021-07-02 01:56 UTC, merged